# Generated by Django 4.2.17 on 2024-12-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Num_of_Crawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csdn_count", models.IntegerField(default=5)),
                ("cnblogs_count", models.IntegerField(default=5)),
                ("juejin_count", models.IntegerField(default=5)),
                ("github_count", models.IntegerField(default=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_data",
                        to="Login.customuser",
                    ),
                ),
            ],
        ),
    ]
